@startuml
package "Zull 集群" {
[Zull实例A]
[Zull实例B]
[Zull实例C]
}
package "Service 集群" {
[微服务A实例1]
[微服务A实例2]
[微服务A实例3]
}
[Mobile Client]-->[Zull实例A]
[Web Client]-->[Zull实例B]
[Other Client]-->[Zull实例C]

[Zull实例A]-->[微服务A实例1]
[Zull实例B]-->[微服务A实例2]
[Zull实例C]-->[微服务A实例3]

@enduml