@startuml
[Config Server]
[微服务A]
[微服务B]
[其他服务..]
[Git Respository]

[微服务A]..>[Config Server]:获取配置
[微服务B]..>[Config Server]:获取配置
[其他服务..]..>[Config Server]:获取配置
[Config Server]..>[Git Respository]:远程获取
 @enduml