@startuml

package "插件化工程模型" {
[App壳工程]
}

package "业务APP" {
[App壳工程]-->[其他业务...]
[App壳工程]-->[C业务APP]
[App壳工程]-->[B业务APP]
[App壳工程]-->[A业务APP]
}
package "功能组件" {

功能-->[网络请求组件]
功能-->[图片加载组件]
功能-->[Common组件]
功能-->[视频播放组件]
功能-->[其他功能...]

[A业务APP]-->功能
[B业务APP]-->功能
[C业务APP]-->功能
[其他业务...]-->功能
}
@enduml