@startuml

[A业务包] -down--> [B业务包]
[B业务包] -right--> [C业务包]
[C业务包]-up--> [D业务包]

[A业务包] -right--> [D业务包]
[B业务包] -up--> [A业务包]
[D业务包] -down--> [C业务包]
[D业务包] -left--> [A业务包]
[A业务包] --> [C业务包]
[C业务包] --> [A业务包]
@enduml