@startuml
[主工程] --> [A业务包]
[主工程] --> [B业务包]
[主工程] --> [C业务包]
[主工程] --> [其他包...]

[依赖库] --> [网络请求库]
[依赖库] --> [图片加载库]
[依赖库] --> [事件订阅库]
[依赖库] --> [其他库...]

[A业务包]-->[依赖库]
[B业务包]-->[依赖库]
[C业务包]-->[依赖库]
[其他包...]-->[依赖库]
 @enduml